theme: jekyll-theme-merlot
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <header>
        <div class="hd_gl">
            <div class="block_hd">Home</div>
            <div class="block_hd">Portfolio</div>
            <div class="block_hd">About Us</div>
            <div class="block_hd">Contact</div>
        </div>
        <div class="text_hd">
            <div class="text_block">
                <b>OUR STRONG
                    &nbsp; ORGANISATION</b>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam aperiam facilis amet esse quisquam in
                    quod praesentium consectetur illum suscipit autem dolorem ea perferendis cumque expedita saepe, id
                    deleniti iure?</p>

                <div class="button">Contact Us</div>

            </div>
            <div class="text_block">
                <div class="img1">
                    <ion-icon name="play-circle-outline"></ion-icon>
                </div>
            </div>
        </div>
    </header>
    <section class="first">
        <div class="sec1">
            <div class="sec1_text">
                <b>Do you know we can
                    provide for you ?</b>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit ipsa iusto similique quo.
                    Sequi explicabo repellendus qui beatae eos illum molestiae tempore harum cum laboriosam temporibus
                    nobis minus, odit quod!</p>
            </div>
            <div class="sec1_button">
                <button>
                    learn more
                </button>
            </div>
        </div>
        <div class="sec1">
            <div class="cont">
                <div class="sec1_block">
                    <ion-icon name="settings-outline"></ion-icon>
                    <b>Management</b>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores officiis eos quas, eligendi unde
                        repellendus officia minima natus odit, cumque, vero ducimus praesentium provident. Dolor officia
                        atque commodi tempora itaque.</p>
                </div>
                <div class="sec1_block">
                    <ion-icon name="pencil-outline"></ion-icon>
                    <b>UI /UX Design</b>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde voluptatum doloribus dolores fugiat
                        laudantium iste veritatis perferendis ducimus porro quibusdam sit eos sed laboriosam,
                        reprehenderit,
                        deserunt, ipsum id doloremque nemo.</p>
                </div>
            </div>
            <div class="cont">
                <div class="sec1_block">
                    <ion-icon name="diamond-outline"></ion-icon>
                    <b>Logo / Branding</b>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde voluptatum doloribus dolores fugiat
                        laudantium iste veritatis perferendis ducimus porro quibusdam sit eos sed laboriosam,
                        reprehenderit,
                        deserunt, ipsum id doloremque nemo.</p>
                </div>
                <div class="sec1_block">
                    <ion-icon name="car-outline"></ion-icon>
                    <b>Animation</b>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde voluptatum doloribus dolores fugiat
                        laudantium iste veritatis perferendis ducimus porro quibusdam sit eos sed laboriosam,
                        reprehenderit,
                        deserunt, ipsum id doloremque nemo.</p>
                </div>
            </div>
        </div>
    </section>
    <section class="second">
        <div class="sec2_hd">
            <b>
                Feature products
            </b>
            <p>
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam, ad quae cum similique modi minima porro
                eum sequi unde. Amet vitae, harum iste architecto itaque similique non ratione atque facilis?
            </p>
            <div class="border"></div>
        </div>
        <div class="sec2_gl">
            <div class="sec2_nav">
                <a href="#">
                    <p>ALL</p>
                </a>
                <a href="#">
                    <p>PRINT TAMPLATE</p>
                </a>
                <a href="#">
                    <p>WEB TAMPLATE</p>
                </a>
                <a href="#">
                    <p>USER INTERFACE</p>
                </a>
                <a href="#">
                    <p>MOCK-UP</p>
                </a>
            </div>
            <div class="gallery">
                <div class="img2"><img src="img/Снимок.PNG" alt=""></div>
                <div class="img2"><img src="img/Снимок.PNG" alt=""></div>
                <div class="img2"><img src="img/Снимок.PNG" alt=""></div>
                <div class="img2"><img src="img/Снимок.PNG" alt=""></div>
                <div class="img2"><img src="img/Снимок.PNG" alt=""></div>
                <div class="img2"><img src="img/Снимок.PNG" alt=""></div>
                <div class="img2"><img src="img/Снимок.PNG" alt=""></div>
                <div class="img2"><img src="img/Снимок.PNG" alt=""></div>
                <div class="img2"><img src="img/Снимок.PNG" alt=""></div>
            </div>
        </div>
        <div class="left">
            <b>Meet our team</b>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Maiores doloribus repudiandae molestiae sequi.
                Quaerat omnis, voluptatem reiciendis tenetur dicta impedit sunt excepturi ex provident sequi illo
                dolorum modi, perferendis maiores!
            </p>
            <div class="border2"></div>
        </div>
        <div class="block_sec">
            <div class="block_sec1">
                <img src="img/Снимок2.PNG" alt="">
            </div>
            <div class="block_sec1_1">
                <b>Mark waugh</b>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas voluptatibus, ducimus sit delectus
                    similique possimus alias, reiciendis laboriosam, quia quisquam cum itaque sunt vitae minima aliquid
                    aut sed consequuntur expedita?</p>
                <div class="i">
                    <i>Facebook</i>
                    <i>Dribble</i>
                    <i>Behance</i>
                    <i>Twiter</i>
                </div>
                <div class="sec1_1_gal">
                    <img src="img/Снимок3.PNG" alt="">
                    <img src="img/Снимок3.PNG" alt="">
                    <img src="img/Снимок3.PNG" alt="">
                    <img src="img/Снимок3.PNG" alt="">
                </div>
            </div>
        </div>
    </section>
    <section class="third">
        <B>Design tips, tricks, and freebies. Delivered weekly.</B>
        <P>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aliquam fugit molestias, aut optio eius enim
            consequuntur deleniti doloribus cupiditate aperiam expedita natus iusto nulla aspernatur ea! Laboriosam
            iusto praesentium deserunt.</P>
        <div class="form">
            <form action="">
                <input type="email">
            </form>
            <button>Subscribe</button>
        </div>
    </section>
    <section class="forth">
        <div class="left">
        <b>Get in touch</b>
        <p>Lorem ipsum dolor sit amet, consectetur adipis cing elit, sed do eiusmod tempor incididunt ut labore et.ur
            adipis cing elit, sed do eiusmod tempor incididunt ut labore et. ur adipis cing elit, sed do eiusmod tempor
            incididunt ut labore et.</p>
        <div class="border2"></div>
    </div>  
    <div class="end">
            <div class="form_end">
                <form action="">
                    <input type="email">
                    <input type="text">
                    <textarea name="" id="" cols="30" rows="10">Type your massage</textarea>
                </form>
                <button>Send massage</button>
            </div>
            <div class="text_end">
                <b>CONTACT INFO</b>
                <P>Jalalabad 24 / A, Ambaarkhana, Sylhet, 
                    Bangladesh</P>
                    <P>redwan@deviserweb.com</P>
                    <p>(+88) 017 617 46373</p>
            </div>
    </div>
    </section>
    <footer>
        <div class="copy">© Copyright @Junaed 2016, All rights reserved.</div>
        <div class="icon">
            <ion-icon name="logo-twitter"></ion-icon>
            <ion-icon name="logo-instagram"></ion-icon>
            <ion-icon name="logo-google"></ion-icon>
            <ion-icon name="logo-facebook"></ion-icon>
        </div>
    </footer>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>
